export enum CommentType {
  APPROVAL_COMMENT = 'APPROVAL_COMMENT',
  APPROVAL_COMMENT_REPLY = 'APPPROVAL_COMMENT_REPLY',
  RUN_STEP_COMMENT = 'RUN_STEP_COMMENT',
  BLACK_LINE_COMMENT = 'BLACK_LINE_COMMENT',
  RED_LINE_COMMENT = 'RED_LINE_COMMENT',
  RUN_CLOSEOUT_COMMENT = 'RUN_CLOSEOUT_COMMENT',
  RUN_CLOSEOUT_COMMENT_REPLY = 'RUN_CLOSEOUT_COMMENT_REPLY',
  RUN_CLOSEOUT_STICKY_COMMENT = 'RUN_CLOSEOUT_STICKY_COMMENT'
}
