export enum ValidationErrors {
  NUM_OUT_OF_BOUNDS = 'NUM_OUT_OF_BOUNDS',
  FIELD_REQUIRED = 'FIELD_REQUIRED',
  TEXT_TOO_SHORT = 'TEXT_TOO_SHORT',
  TEXT_TOO_LONG = 'TEXT_TOO_LONG',
  STEP_WITNESS_SIGNATURE_REQUIRED = 'STEP_WITNESS_SIGNATURE_REQUIRED',
  STEP_INSPECTION_SIGNATURE_REQUIRED = 'STEP_INSPECTION_SIGNATURE_REQUIRED',
}
